version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: erp_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: erp_comercial
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - erp_network

volumes:
  mysql_data:

networks:
  erp_network:
    driver: bridge